added verification to commits_per_day endpoint. works with repository…
Gitalytics-org/gitalytics.org pull request #56
Opened 2023-03-01 11:18 UTC by Benni0706

…_access

2023-03-01 14:04 UTC, JuliusJaenchen requested changes

2023-03-01 14:04 UTC, JuliusJaenchen commented on src/backend/gitalytics_api/routes/get_commits_per_day.py
>  @router.get("/commits_per_day/", response_model=ResponseModel)
```suggestion
@router.get("/commits_per_day", response_model=ResponseModel)
```

2023-03-01 14:04 UTC, JuliusJaenchen commented on src/backend/gitalytics_api/routes/get_commits_per_day.py
>              .filter(dbm.Repository.workspace_id == workspace_id) \
fehlt nicht ein ".filter(dbm.Session == session)" oder so? Dass kann so ja nicht funktionieren, da die mitgegebene Session gar nicht verwendet wird...

2023-03-01 16:16 UTC, Benni0706 commented on src/backend/gitalytics_api/routes/get_commits_per_day.py
>  @router.get("/commits_per_day/", response_model=ResponseModel)
Ohne das würden die Parameter nicht funktionieren, ist die normale Syntax

2023-03-01 18:49 UTC, JuliusJaenchen commented on src/backend/gitalytics_api/routes/get_commits_per_day.py
>  @router.get("/commits_per_day/", response_model=ResponseModel)
bei mir ging es ohne. Ich fand das ziemlich komisch mit einem trailing slash... Dann hat man ja ".../?..."

2023-03-12 20:19 UTC, roriwa commented
depricated

2023-03-12 20:19 UTC, closed without merging